apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: appconfig
      containers:
      - name: nginx
        image: nginx
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 128Mi
        env:
          - name: key_local
            value: data_local
          - name: key1
            valueFrom:
              configMapKeyRef:
                name: appconfig
                key: key1
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_IP_ADDRESS
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        volumeMounts:
          - name: config-volume
            mountPath: /etc/config # vse chto est v appconfig budet dostupno v kataloge /etc/config
          - name: config-volume
            mountPath: /etc/config.txt
            subPath: config.txt # tolko odno pole iz appconfig budet dostupno kak fail /etc/config.txt
