apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  volumes:
    - name: nginx-env-volume
      configMap:
        name: nginx-conf
  containers:
    - name: nginx
      image: nginx
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 100m
          memory: 128Mi
      envFrom:
        - secretRef:
            name: nginx-env
      volumeMounts:
        - name: nginx-env-volume
          mountPath: /etc/nginx/conf.test
          subPath: nginx-config.txt
