apiVersion: v1
kind: Pod
metadata:
  name: nginx-ubuntu
spec:
  containers:
    - image: nginx
      name: nginx
    - image: ubuntu
      name: ubuntu
      command: ["/bin/bash"]
      args: ["-c", "while true; do echo Hello `date`; sleep 100; done"]

