apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp-taint
  labels:
    type: front
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 128Mi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: usercase
                  operator: In
                  values:
                    - "workload"
      tolerations:
        - effect: NoSchedule
          key: dedicated
          value: "true"
