apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-int
spec:
  # ClusterIP (default), NodePort, LoadBalancer
  type: ClusterIP
  selector:
    app: httpd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
