apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-ext
spec:
  # ClusterIP (default), NodePort, LoadBalancer
  type: LoadBalancer
  selector:
    app: httpd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
