apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-sts
spec:
  serviceName: kafka-ssz
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: nginx
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - name: kafka-pvc
              mountPath: /var/data
  volumeClaimTemplates:
    - metadata:
        name: kafka-pvc
      spec:
        storageClassName: yc-network-ssd
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi

